'use strict';

var jqmControllers = angular.module('jqmControllers');

jqmControllers.controller('µProfileListCtrl', function($scope, $http, µProfileDto)
{
    $scope.items = null;
    $scope.selected = [];

    $scope.sortvar = 'name';

    $scope.save = function()
    {
        // Save and refresh the table - ID may have been generated by the server.
    	µProfileDto.saveAll({}, $scope.items, $scope.refresh);
    };

    $scope.refresh = function()
    {
        $scope.selected.length = 0;
        $scope.items = µProfileDto.query();
    };
    
    $scope.remove = function()
    {
        var q = null;
        for ( var i = 0; i < $scope.selected.length; i++)
        {
            q = $scope.selected[i];
            µProfileDto.delete({id: q.id});
            $scope.items.splice($scope.items.indexOf(q), 1);
        }
    };
    
    $scope.newProfile = function()
    {
    	var n = {description: "short description", name: "new profile"};
    	$scope.items.push(n);
    	$scope.selected[0] = n;
    }

    $scope.filterOptions = {
        filterText : '',
    };

    $scope.gridOptions = {
        data : 'items',
        enableCellSelection : true,
        enableRowSelection : true,
        enableColumnResize : true,
        enableCellEditOnFocus : true,
        multiSelect : true,
        showSelectionCheckbox : true,
        selectWithCheckboxOnly : true,
        selectedItems : $scope.selected,
        showGroupPanel : false,
        filterOptions : $scope.filterOptions,
        plugins :  [new ngGridFlexibleHeightPlugin()],
        columnDefs : [
                {
                    field : 'name',
                    displayName : 'Name',
                    width : '**',                  
                },
                {
                    field : 'description',
                    displayName : 'Description',
                    width : '**',
                },]
    };

	$scope.refresh();
});
